# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StandwoodTask' do
  pod 'StanwoodCore'
	
  target 'StandwoodTaskTests' do
    inherit! :search_paths
  end
end
